### PR TITLE
Add Overcast Network repo and update SportBukkit version

### PR DESCRIPTION
**Pull request by Yukon**
SportBukkit version update is required in order for it to compile with new BlockDispenseEntityEvent.

### CODE REVIEW

**Comment by Yukon** [comment]
This should be pulled or people can not compile without fixing this themselves.

**Comment by skipperguy12** [comment]
This needs to be added. I spent an hour trying to see what was wrong with the compile, I had to add it manually.

**Comment by tonybruess** [comment]
YOU DARE USE THE BIG GREEN MERGE BUTTON???  -_-

**Comment by Yukon** [comment]
LOL He pushed the big green button!!

**Comment by Yukon** [comment]
GitHub needs a option to configure how PR are merged.

**Comment by steveanton** [comment]
Is there something wrong with it? :S

**Comment by Yukon** [comment]
It looks neater if you Pull, Squash, then Merge (Got that from Apple). Does not have the extra commit that is not needed. But one plus I discovered is it keeps the orignal commit time but you still should do PSM.

**Pull request merged**
