### PR TITLE
Transfer TNT ownership through explosion chains

### PR DESCRIPTION
**Pull request by jedediah**

### CODE REVIEW

**Comment by tonybruess** [comment]
Merge it :+1:

**Comment by jengel3** [comment]
Wouldn't this kinda encourage people to blow up other player's TNT?

**Comment by tonybruess** [comment]
How so? If you blow up a teammates TNT, you look like a team griefer. If you manage to blow up enemy TNT, you get the kill.

**Comment by tonybruess** [comment]
Looks good to merge

**Pull request merged**
